image: Visual Studio 2017
version: 4.0.{build}
configuration: Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
cache:
  - packages
before_build:
  - dotnet restore
clone_depth: 1
install:
  - ps: .\SetAppVeyorBuildVersion.ps1
build_script:
  - ps: .\Build.ps1
after_build:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "artifacts\code-coverage.xml"
pull_requests:
  do_not_increment_build_number: true
artifacts:
- path: 'artifacts\*.nupkg'
  name: Nuget
test: off
